#!/bin/bash

THIS_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

STDOUT=$THIS_DIR/stdout
APP=$THIS_DIR/bin/Debug/vmacs/vmacs

cd $THIS_DIR
if ! ./build; then
  exit 1
fi

if ! open -na iTerm.app $THIS_DIR/run; then
  exit 1
fi

sleep 1
lldb -n vmacs

rm $STDOUT
