#!/bin/bash

# This will open the app in new iTerm so we can debug stdout.
THIS_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

STDOUT=$THIS_DIR/stdout
APP=$THIS_DIR/bin/Debug/vmacs/vmacs

cd $THIS_DIR
if ! ./build; then
  exit 1
fi

touch $STDOUT

if ! open -na iTerm.app $THIS_DIR/run; then
  exit 1
fi

watch -n 0.1 tail $STDOUT
rm $STDOUT
