#!/bin/bash

THIS_DIR=$(realpath $(dirname "${BASH_SOURCE[0]}"))

APP=$THIS_DIR/bin/Debug/vmacs/vmacs
STDOUT=$THIS_DIR/stdout


cd $THIS_DIR
if ! ./build; then
  exit 1
fi


cd $THIS_DIR/.. # otherwise new iTerm.app start at ~
if ! $APP $@; then
  exit 1
fi


